# File: .github/workflows/main.yml

name: Run Azure Login With a Service Principal Secret
on:
  # Triggers the workflow automatically on a push to the main branch
  push:
    branches:
      - main
      
  # Triggers the workflow manually via the GitHub UI
  workflow_dispatch:

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
